### ISSUE TITLE
instanceof doesn't work as expected for some inheritance patterns

### ISSUE THREAD

**Issue by docmarionum1** [DrkSephy/legionJS#3]
Currently some of the available inheritance patterns don't maintain the expected instanceof results.

For example, this works:

A = legion.Class.extend({});
B = A.Class.extend({});

b = new B();

b instanceof legion.Class; //true
b instanceof A //true
b instanceof B //true

But these don't:

A = legion.Class.extend({});
B = legion.Class.extend(A);

b = new B();

b instanceof legion.Class; //true
b instanceof A //false
b instanceof B //true

A = legion.Class.extend({});
B = legion.Class.extend({});
AB = legion.Class.extend([A, B]);

ab = new AB();

ab instanceof legion.Class; //true
ab instanceof A; //false
ab instanceof B; //false
ab instanceof AB; //true

The issue is that when passed an existing Class, there is no way to merge that Class's prototype chain with the current class's chain.  

If we don't care about maintaining instanceof, we could ignore this, or create our own Class.instanceof() method to use.  

Or we could also change the paradigm so that it would make more sense to the user, for example using Java's single inheritance + implements.

For example:

// extend(['array', 'of', 'implementations'], {})
Player = legion.Class.extend([legion.Input, legion.Net], {name: "doc"});
var p = new Player();
p instanceof legion.Class; //true
p instanceof Player; //true
p instanceof legion.Input; //false, as intended
p instanceof legion.Net; //false, as intended

Or another model, having an implements function so:

Player = legion.Class.extend({name: "doc"}).implements([legion.Input, legion.Net]);

or it could also be written as:

Player = legion.Class.implements([legion.Input, legion.Net]).extend({name: "doc"});

This would also allow you to more logically do something like:

Character = legion.Class.extend({name: "doc"});
PlayerCharacter = Character.implements([legion.Input]);
NPC = Character.implements([AI]);

What are your thoughts on it?

**Comment by DrkSephy** [comment]
I would go with the last bit, to make it seem more logical to the user. The easier the API is to understand to the user, the better.

**Comment by docmarionum1** [comment]
Alright, I'll implement it that way.
