### ISSUE TITLE
Create concrete milestone for a legion 0.1.0?

### ISSUE THREAD

**Issue by docmarionum1** [DrkSephy/legionJS#58]
I was thinking maybe we should have some sort of overall functionality goal that we can group tasks into and then shoot for a date.

For example, maybe for a first goal we could say we want to do "multiplayer pong over the internet".  For that we would need to implement (at least): Sync (#54, #55, #56), Resource loader (#36), Collision (#21, #22).  Then we could pull those all out into a version 0.1.0/functional pong milestone and have something more concrete we're working towards, rather than just abstract features.  

What do you guys think?

**Comment by docmarionum1** [comment]
Obviously, version # is up for debate.  It won't be particularly feature-rich, so maybe 0.0.1 would be more fitting ;)

**Comment by DrkSephy** [comment]
I think that's a good starting point. Being able to build a small, simple game would be a good time for the first release. We'll go with 0.1.0, based on semantics [here](http://stackoverflow.com/questions/615227/how-to-do-version-numbers).

**Comment by docmarionum1** [comment]
K, what about a due date?  Would March 31st be too ambitious?

**Comment by DrkSephy** [comment]
I say we go for the 31st.
