### ISSUE TITLE
Setup Documentation Build

### ISSUE THREAD

**Issue by docmarionum1** [DrkSephy/legionJS#63]
We should have a doc build system in place that can parse our inline docstrings and also add additional tutorials and such.

**Comment by docmarionum1** [comment]
jsdoc3 seems to be the defacto tool.  Never used it myself, have you, @DrkSephy?

**Comment by docmarionum1** [comment]
For my own reference: http://usejsdoc.org/index.html

**Comment by DrkSephy** [comment]
I've never used it, but I've seen it used in virtually every JavaScript Documentation site ever. We should go with it.

**Comment by chessmasterhong** [comment]
I've used JSDoc before and can set up a basic documentation build. Are there any requirements that you would like?

**Comment by docmarionum1** [comment]
Thanks @chessmasterhong 

Want it to build an API doc from docstrings in the /src directory and also have separate tutorial docs in a /docs directory.

It would also be helpful if you could give David and I a small example of proper docstring format so it gets picked up, and a list of all the places that we should make sure to have docstrings (file/module level, class variables, functions, etc.)
