### ISSUE TITLE
Create Legion Organization to Centralize Legion Repos

### ISSUE THREAD

**Issue by docmarionum1** [DrkSephy/legionJS#74]
I think we talked about this before - we should create a legion organization on github so we can centralize any repos in one place - at least the core repo and example repo for now and then any others down the line.  Best to do it before we "launch" 0.1.0 so we can have a permanent link going forward.

**Comment by DrkSephy** [comment]
Organization was created here: https://github.com/legionJS.

**Comment by docmarionum1** [comment]
+π

**Comment by docmarionum1** [comment]
Oh, do you need to update Travis?  Or will it just pick up the change?

**Comment by DrkSephy** [comment]
It looks like it will pick up the change automatically when run on their servers, it's not something we configure on our end.
